### ISSUE TITLE
Finir le projet

### ISSUE THREAD

**Issue by TidyMaze** [TidyMaze/projetTestOutils#1]
VITE !!!

**Comment by Nat-Faeeria** [comment]
Hmmmm ... sinon on peut faire des probas ?

**Comment by TidyMaze** [comment]
¡ soɹƃ sᴉɹd doɹʇ sɐ uǝ,┴

**Comment by gpouilloux** [comment]
M. Rolland, vous êtes prié de terminer le projet avant ce soir 23:55.
==================================

Merci :-)

**Comment by gpouilloux** [comment]
Projet terminé : [Lien](http://tidymaze.github.io/projetTestOutils)
