### ISSUE TITLE
Le logiciel est pourri !

### ISSUE THREAD

**Issue by math-th** [TidyMaze/projetTestOutils#3]
ça fait rien, ça sert à rien, à refaire !

Grève demain !

**Comment by Nat-Faeeria** [comment]
Je corrige le ticket : grève demain.

**Comment by TidyMaze** [comment]
Et sinon, ça compile ?

**Comment by gpouilloux** [comment]
Mylyn & GitHub & Eclipse

http://download.eclipse.org/egit/github/updates-nightly

**Comment by gpouilloux** [comment]
http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.mylyn.github.doc%2Fhelp%2FEGit%2FGitHub%2FUser_Guide%2FUser-Guide.html
